### PR TITLE
Compute `app-server` defaults based on node features.

### PR DESCRIPTION
**Pull request by riccardomurri**
The computed defaults will be incorrect in case the `app-server` node
has different hardware/flavor than the compute nodes, but I am
speculating this is a minority case and you would need to provide the
correct values in the `setup.yml` file anyway.

The change is motivated by having single-node deployments 
on large virtual machines (a common case at Pelkmans Lab)
do the right thing without additional configuration.

### CODE REVIEW

**Comment by hackermd** [comment]
Nice! I wasn't aware of the `ansible_` resource parameters.

Sensible defaults are generally a bit tricky for a single-node deployment, because web, application and database servers will also require resources and may end up competing for CPU and memory. But I guess that the kernel will be able to manage that!?

**Comment by riccardomurri** [comment]
> Sensible defaults are generally a bit tricky for a single-node
> deployment, because web, application and database servers will also
> require resources and may end up competing for CPU and memory. But I
> guess that the kernel will be able to manage that!?

I'd say let the Linux kernel manage it as a first approximation.

When we have a clearer picture of what fraction of resources is needed
by each subsystem (web, DB, etc) we can refine the values.

**Comment by hackermd** [comment]
> The computed defaults will be incorrect in case the app-server node
has different hardware/flavor than the compute nodes, but I am
speculating this is a minority case and you would need to provide the
correct values in the setup.yml file anyway.

This would pose a problem for most multi-node cluster deployments. In those cases one would probably like to configure resources manually.

We should document the individual parameters for each role either in the [docs](http://docs.tissuemaps.org/installation.html#tmdeploy) or in separate `README` files for each role directory of the `tmdeploy` repository.

**Comment by hackermd** [comment]
The same logic using `ansible_` variables to calculate sensible defaults could be used for the database server roles.

**Pull request merged**
